apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec:
  containers:
  - image: nginx
    name: readyme
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    -  containerPort: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8081
      initialDelaySeconds: 2
      periodSeconds: 8

---

apiVersion: v1
kind: Pod
metadata:
  name: livenesscheck
spec:
  containers:
  - image: busybox
    name: app
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    args:
    - /bin/sh
    - -c
    - while true; do touch /tmp/test.txt; sleep 36; rm -f /tmp/test.txt; sleep 600; done;
    livenessProbe:
      exec:
        command:
        - cat /temp/test.txt
      initialDelaySeconds: 5
      periodSeconds: 5

---

apiVersion: v1
kind: Pod
metadata:
  name: health-check-demo
spec:
  containers:
  - name: web-app
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 15
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3

---

apiVersion: v1
kind: Pod
metadata:
  name: startupcheck
spec:
  containers:
  - image: httpd:2.4.46
    name: http-server
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    startupProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 15