apiVersion: v1
kind: Pod
metadata:
  name: initpod
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  initContainers:
  - name: delay
    command: ["sleep", '45']
    image: busybox