apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-flow
spec:
  podSelector:
    matchLabels:
      app: BE
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: FE