apiVersion: v1
kind: Pod
metadata:
  name: nginx-env
spec:
  containers:
  - image: nginx
    name: cont1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: PROFILE
      value: prod
    - name: VERSION
      value: '1.0'