apiVersion: v1
kind: Pod
metadata:
  name: nginxsa
spec:
  serviceAccount: custom
  containers:
  - image: nginx:1.18.0
    name: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"