apiVersion: v1
kind: Pod
metadata:
  name: volume-app
spec:
  volumes:
  - name: logvol
    emptyDir: {}
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /var/logs
      name: logvol