apiVersion: v1
kind: Pod
metadata:
  name: ping
spec:
  containers:
  - image: busybox
    name: pingmain
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["ping"]
    args: ["kubernetes.io"]