apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - name: secure-container
    image: busybox
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]

---

apiVersion: v1
kind: Pod
metadata:
  name: securitydemo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: secvol
    emptyDir: {}
  containers:
  - name: cont1
    image: busybox
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: [ “sh”, “-c”, “sleep 1h” ]
    volumeMounts:
    - name: secvol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false

---

apiVersion: v1
kind: Pod
metadata:
  name: rootcheck
spec:
  containers:
  - image: nginx:1.18.0
    name: seccontainer
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      runAsNonRoot: true

---

apiVersion: v1
kind: Pod
metadata:
  name: security-demo
spec:
  containers:
  - image: nginx
    name: security-demo
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
  restartPolicy: Never