kind: Pod
apiVersion: v1
metadata:
  name: sidecarpattern
spec:
  volumes:
  - name: log-vol
    emptyDir: {}
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    args: ["-c", "while true; do date >> /var/log/nginx/date.txt; sleep 10;done"]
    volumeMounts:
    - name: log-vol
      mountPath: /var/log/nginx
  - name: sidecar
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: log-vol
      mountPath: /var/log/nginx/date.txt