apiVersion: v1
kind: Pod
metadata:
  name: adapterpod
spec:
  volumes:
  - name: logs
    emptyDir: {}
  containers:
  - name: app
    image: alpine
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/app.log; sleep 2;done"]
    volumeMounts:
    - name: logs
      mountPath: /var/log
  - name: adapter
    image: alpine
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["/bin/sh"]
    args: ["-c", "tail -f /var/log/app.log | sed -e 's/^/DateChanged /' > /var/log/out.log"]
    volumeMounts:
    - name: logs
      mountPath: /var/log