apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-using-docker-pvc
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: docker-storage
  volumes:
  - name: docker-storage
    persistentVolumeClaim:
      claimName: docker-pvc